# Create Numpy Array

In [1]:
import numpy as np

np_array_1d = np.array([1,2,3]) 
print(type(np_array_1d)) # 看type
print(np_array_1d.shape)
print(np_array_1d)       # 看內容

np_array_2d = np.array([[1, 2], [3, 4]]) 
print(type(np_array_2d))
print(np_array_2d.shape) # .shape 看是幾乘幾
print(np_array_2d)       # 看內容
print(np_array_2d.ndim)  # .ndim 看維度
print(np_array_2d.size)  # .size 看有幾個元素

<class 'numpy.ndarray'>
(3,)
[1 2 3]
<class 'numpy.ndarray'>
(2, 2)
[[1 2]
 [3 4]]
2
4


In [2]:
import numpy as np

x = np.array([1, 2])   # datatype =dtype 預設型別
print(x.dtype)        

x = np.array([1.0, 2.0])   
print(x.dtype)          

x = np.array([1, 2], dtype=np.int64)   # 指定特定型態
print(x.dtype)           

int32
float64
int64


In [19]:
import numpy as np
np_array_zeros = np.zeros([3,4,2]) # .zeros 內容為0 ，3個4*2
np_array_ones = np.ones([2,3]) # .ones 內容為1 的2*3
np_array_full = np.full([3,2], 5) #3*2 裡面都是5
np_array_eye = np.eye(2)   #2*2 对角线的地方为1，其余的地方为0
np_random = np.random.random((2,2)) #2*2 裡面數字隨機

np_arange = np.arange(4) # 0~4 4不算  .arange給一個範圍 變成array

#  .linspace畫圖很常用!!! 
np_linspace = np.linspace(0, 2*np.pi, 5) #0~2pi 之間產生5個均分點

print(np_array_zeros)
print(np_array_ones)
print(np_array_full)
print(np_array_eye)
print(np_random)
print(np_arange)
print(np_linspace)

#arr2[1,1] = np.nan  # not a number
#arr2[1,2] = np.inf  # infinite

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0.]
 [0. 1.]]
[[0.42973933 0.82376577]
 [0.00105144 0.69152493]]
[0 1 2 3]
[0.         1.57079633 3.14159265 4.71238898 6.28318531]


# Basic Arithmetic  /əˈrɪθ.mə.tɪk/  算術

In [2]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum  # Elementwise是按位置 
#示範 兩種寫法都一樣
print(x + y)
print(np.add(x, y))
print('==============')

# Elementwise difference
print(x - y)
print(np.subtract(x, y))
print('==============')

# Elementwise product
print(x * y)
print(np.multiply(x, y))
print('==============')

# Elementwise division
print(x / y)
print(np.divide(x, y))
print('==============')

# Elementwise square root   對X開更號
print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


# Matrix Algebra  /ˈmeɪ.trɪks /ˈæl.dʒə.brə/ 矩陣代數

In [3]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors [內積] 同位置相乘+同位置相乘
#示範 兩寫法都一樣
print(v.dot(w)) 
print(np.dot(v, w))
print('==============')

# Matrix / vector product [矩陣.向量相乘]
print(x.dot(v))
print(np.matmul(x, v))  #.matmul 矩陣相乘 matrix multiplication縮寫
print('==============')

# Matrix / matrix product [矩陣相乘]
print(x.dot(y))
print(np.dot(x, y))
print('==============')

# Matrix transpose  [矩陣反轉]
print(x)
print(x.T)
print('==============')

# Matrix inverse [矩陣求逆]
print(x)
print(np.linalg.inv(x)) #線性代數縮寫
print('==============')

# Matrix determinant [矩陣求行列式]
print(x)
print(np.linalg.det(x))
print('==============')

# SVD [奇异值分解（singular Value Decomposition）] 假如有一个矩阵A，对它进行奇异值分解，可以得到三个矩阵
U, S, V = np.linalg.svd(x)
print(U)
print(S) # s 是對角矩陣
print(V)


219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 2]
 [3 4]]
-2.0000000000000004
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
[5.4649857  0.36596619]
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


# Comparison 相同位置逐個比較是否符合條件

In [33]:
a = np.array([[1, 1, 2], [2, 3, 5]])
b = np.array([[1, 3, 2], [3, 3, 1]])

print(a == b)
print(a >= b)

[[ True False  True]
 [False  True False]]
[[ True False  True]
 [False  True  True]]


# Sorting 排序 

In [9]:
a = np.array([[1, 5, 2], [7, 1, 3]])

print(np.sort(a, axis=0)) #排序 由小到大 按列
print(np.sort(a, axis=1)) #排序 由小到大 按行
print('======')

b = np.array([[1, 5, 2], [7, 1, 3]])
b.sort(axis=0)
print(b)

[[1 1 2]
 [7 5 3]]
[[1 2 5]
 [1 3 7]]
[[1 1 2]
 [7 5 3]]


# Statistical Computations  統計計算

In [5]:
x = np.array([[1,2],[3,4]], dtype=np.float64)

print("Mean 平均值: {}".format(x.mean()))
print("Max 最大值: {}".format(x.max()))
print("Min 最小值: {}".format(x.min()))
print("Std 標準差: {}".format(x.std()))
print("Var 變異數: {}".format(x.var()))
print("Sum 總和: {}".format(x.sum()))

# Row wise and column wise min
print("欄的方向 sum: {}".format(np.sum(x, axis=0)))
print("列的方向 sum: {}".format(np.sum(x, axis=1)))
print("欄的方向 minimum: {}".format(np.min(x, axis=0)))
print("列的方向 minimum: {}".format(np.min(x, axis=1)))

#累加總合 1，1+2，1+2+3，1+2+3+4
print("Cumulative sum: {}".format(np.cumsum(x))) 

Mean 平均值: 2.5
Max 最大值: 4.0
Min 最小值: 1.0
Std 標準差: 1.118033988749895
Var 變異數: 1.25
Sum 總和: 10.0
欄的方向 sum: [4. 6.]
列的方向 sum: [3. 7.]
欄的方向 minimum: [1. 2.]
列的方向 minimum: [1. 3.]
Cumulative sum: [ 1.  3.  6. 10.]


In [6]:
x = np.array([[1,4],[2,3]], dtype=np.float64)
print(x)

# argmax回傳最大數的index，用列比
# 1比2 2大所以回傳其索引
# 2比4 4大所以回傳其索引
print("argmax(axis=0): {}".format(np.argmax(x, axis=0)))

# argmax回傳最大數的index，用行比
print("argmax(axis=1): {}".format(np.argmax(x, axis=1)))


[[1. 4.]
 [2. 3.]]
argmax(axis=0): [1 0]
argmax(axis=1): [1 1]


#  Indexing & Slicing 用索引選取範圍 切割

In [7]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

#以下兩寫法 都是一樣的
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a = np.arange(1, 13).reshape(3,4)


#現在想切出 這一塊
# [[2 3]
#  [6 7]]
print(a[:2, 1:3]) #0~2 2不算

#可對索引位置改數字
print(a[0, 1])   #索引位置 a的 [0,1]
a[0, 1] = 77    
print(a[0, 1])   

[[2 3]
 [6 7]]
2
77


In [10]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

r1 = a[1, :]    # 維度只有一
r2 = a[1:2, :]  # 兩邊都有冒號 維度二
print(r1, r1.shape) 
print(r2, r2.shape)  

print('=====================')

c1 = a[:, 1]     # 維度只有一
c2 = a[:, 1:2]   # 兩邊都有冒號 維度二
print(c1, c1.shape)  
print(c2, c2.shape)   

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [12]:
import numpy as np 
a = np.arange(10) 
print(a)
b = a[2:7:2]  #2~7 7不算 每間隔2個
print(b)
print('=============')

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)  

# slice items starting from index
print('Now we will slice the array from the index a[1:]') 
print(a[1:])

# this returns array of items in the second column 
print('The items in the second column are:')  
print(a[:,1]) 

# Now we will slice all items from the second row 
print('The items in the second row are:') 
print(a[1,:]) 

# Now we will slice all items from column 1 onwards 
print('The items column 1 onwards are:') 
print(a[:,1:])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]
The items in the second column are:
[2 4 5]
The items in the second row are:
[3 4 5]
The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


# Boolean index 可用索引位置判斷是否

In [13]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   #檢查index是否有大於2
print(bool_idx)      

#有以下兩種寫法
print(a[bool_idx])  # Prints "[3 4 5 6]" 有True的地方都會 留下
print(a[a > 2])     # Prints "[3 4 5 6]"


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


# Add/Remove Elements

In [43]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])

a = np.append(a, 10) # 誰要加 加多少
print(a)

a = np.append(a, b)
print(a)



[ 0  1  2 10]
[ 0  1  2 10  3  4  5]


#   List/Tuple 轉換型別成 Numpy Array

In [14]:
my_list = [1,2,3]
my_tuple = (1,2,3) 
numpy_a = np.asarray(my_tuple)  # .asarray 轉型別  把值組轉成array
numpy_b = np.asarray(my_list)   # 也可把List轉成array

print(numpy_a)
print(numpy_b)

list_a = list(numpy_a)
print(list_a)

[1 2 3]
[1 2 3]
[1, 2, 3]


#  Numpy array 跟 Pandas dataframe互轉

In [17]:
import pandas as pd

# load csv file
df = pd.read_csv('na_demo.csv')

numpy_array = np.array(df) #把dataframe 轉成array
print(numpy_array)

print('=====================')
df_from_numpy = pd.DataFrame(numpy_array) #把 array轉成dataframe
print(df_from_numpy)

[['A' 1990 5988 'aa']
 ['B' 1991 5989 'bb']
 ['C' 1992 5990 'cc']
 ['D' 1993 5991 'dd']]
   0     1     2   3
0  A  1990  5988  aa
1  B  1991  5989  bb
2  C  1992  5990  cc
3  D  1993  5991  dd


# Broadcasting   把形狀變一樣
ref: https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html

In [25]:
import numpy as np
a = np.array([0, 1, 2])
b = a + 3  #會把3 變成[3,3,3]去相加
print(b)

M = np.ones((3, 3))  #3*3 內容都1
print(M + a)


[3 4 5]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


#### np.newaxis= None 用來增加維度

In [18]:
a = np.arange(3) 
b = np.arange(3)[:, np.newaxis]  # np.newaxis= None 用來增加維度
c = np.arange(3)[:, None] #跟上面寫法相同

print(a)
print("======")
print(b)
print("======")
print(c)
print("======")
print(a+b)

[0 1 2]
[[0]
 [1]
 [2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [5]:
a = np.arange(3) # [0,1,2] 一維
print(a.shape)
b = np.arange(3)[:, np.newaxis] #二維
print(b.shape)

(3,)
(3, 1)


# Reshape 朔型 & Flatten 變平

In [29]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])  
b=np.reshape(a,(2,-1))   # -1 是給python自己算 把a reshape成2*?
c=np.reshape(a,(2,2,-1))  # 2個 2*3
d=np.reshape(a,(2,3,-1))
print(a)
print('=========')
print(b)
print('=========')
print(c)
print('=========')
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [31]:
a=np.array([[1,2],[3,4],[5,6]])  #原本是三維
print(a.flatten())

[1 2 3 4 5 6]


# Stack  疊堆
ref: https://blog.csdn.net/qq_17550379/article/details/78934529

In [23]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

print('a shape {} / b shape {}'.format(a.shape, b.shape))

print(np.stack((a, b), axis=0))  #向下的方向 去疊
print(np.stack((a, b), axis=0).shape)
print("======")
print(np.stack((a, b), axis=1)) #向右的方向 去疊
print(np.stack((a, b), axis=1).shape)

a shape (3,) / b shape (3,)
[[1 2 3]
 [2 3 4]]
(2, 3)
[[1 2]
 [2 3]
 [3 4]]
(3, 2)


# Copy & Deep Copy

In [24]:
import numpy as np

a = np.arange(4) #[0,1,2,3]
b = a
c = a
d = b

d[1:3] = [22, 33]   # array([0, 22, 33,  3])
print(a)          
print(b)           
print(c)          
print(b is a)

[ 0 22 33  3]
[ 0 22 33  3]
[ 0 22 33  3]
True


In [50]:
b = a.copy()    # deep copy ([0, 22, 33,  3])
print(b)        
a[3] = 44
print(a)        # array([0, 22, 33, 44])
print(b)        # array([11, 22, 33,  3])

[ 0 22 33  3]
[ 0 22 33 44]
[ 0 22 33  3]
