## Gray to BGR

In [1]:
import cv2
import numpy as np
img=np.random.randint(0,256,size=[2,4],dtype=np.uint8) #產生0~256 256不算
rst=cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)  #.cvtColor 轉換

print("img=\n",img) 
print("rst=\n",rst) # 原本的每個元素 會變三層 ex: 39 變三層

img=
 [[ 39 167 101 132]
 [148 112 250  52]]
rst=
 [[[ 39  39  39]
  [167 167 167]
  [101 101 101]
  [132 132 132]]

 [[148 148 148]
  [112 112 112]
  [250 250 250]
  [ 52  52  52]]]


## BGR to RGB

In [2]:
import cv2
import numpy as np
img=np.random.randint(0,256,size=[2,4,3],dtype=np.uint8)
rgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)  # 調順序
bgr=cv2.cvtColor(rgb,cv2.COLOR_RGB2BGR)
print("img=\n",img)
print("rgb=\n",rgb)
print("bgr=\n",bgr)

img=
 [[[165  11 216]
  [ 24 139 110]
  [214 225  10]
  [173 155   3]]

 [[117 159  82]
  [183  70 213]
  [127 116 127]
  [ 52 230 199]]]
rgb=
 [[[216  11 165]
  [110 139  24]
  [ 10 225 214]
  [  3 155 173]]

 [[ 82 159 117]
  [213  70 183]
  [127 116 127]
  [199 230  52]]]
bgr=
 [[[165  11 216]
  [ 24 139 110]
  [214 225  10]
  [173 155   3]]

 [[117 159  82]
  [183  70 213]
  [127 116 127]
  [ 52 230 199]]]


## Real image convert

In [1]:
#RGB<->GRAY
import cv2
lena=cv2.imread("images/lenacolor.png")
gray=cv2.cvtColor(lena,cv2.COLOR_BGR2GRAY)  # BGR 2 GRAY
rgb=cv2.cvtColor(gray,cv2.COLOR_GRAY2BGR)

#==========print shape============
print("lena.shape=",lena.shape) # 三層
print("gray.shape=",gray.shape) # 一層
print("rgb.shape=",rgb.shape)

#==========show images============
cv2.imshow("lena",lena) #從彩色 轉灰色 又要轉彩色，會發現 灰色無法轉成彩色
cv2.imshow("gray",gray)
cv2.imshow("rgb",rgb)
cv2.waitKey()
cv2.destroyAllWindows()

lena.shape= (512, 512, 3)
gray.shape= (512, 512)
rgb.shape= (512, 512, 3)


In [2]:
import cv2
lena=cv2.imread("images/lenacolor.png")
rgb = cv2.cvtColor(lena, cv2.COLOR_BGR2RGB)

cv2.imshow("lena",lena)
cv2.imshow("rgb",rgb)  #順序要B G R 不然會怪怪
cv2.waitKey()
cv2.destroyAllWindows()

## HSV

In [7]:
import cv2
import numpy as np

#=========test blue in HSV=============
imgBlue=np.zeros([1,1,3],dtype=np.uint8) # 一個1*3
print(imgBlue)

imgBlue[0,0,0]=255 # 長.寬 深度index  順序BGR
Blue=imgBlue
BlueHSV=cv2.cvtColor(Blue,cv2.COLOR_BGR2HSV)
print("Blue=\n",Blue)
print("BlueHSV=\n",BlueHSV)

#=========test green in HSV=============
imgGreen=np.zeros([1,1,3],dtype=np.uint8)
imgGreen[0,0,1]=255
Green=imgGreen
GreenHSV=cv2.cvtColor(Green,cv2.COLOR_BGR2HSV)
print("Green=\n",Green)
print("GreenHSV=\n",GreenHSV)

#=========test red in HSV=============
imgRed=np.zeros([1,1,3],dtype=np.uint8)
imgRed[0,0,2]=255
Red=imgRed
RedHSV=cv2.cvtColor(Red,cv2.COLOR_BGR2HSV)
print("Red=\n",Red)
print("RedHSV=\n",RedHSV)

[[[0 0 0]]]
Blue=
 [[[255   0   0]]]
BlueHSV=
 [[[120 255 255]]]
Green=
 [[[  0 255   0]]]
GreenHSV=
 [[[ 60 255 255]]]
Red=
 [[[  0   0 255]]]
RedHSV=
 [[[  0 255 255]]]


## Mask 遮罩 InRange 設定在你要的範圍 只秀出那部分

In [3]:
import cv2
import numpy as np
img=np.random.randint(0,256,size=[5,5],dtype=np.uint8)
min=100
max=200

mask = cv2.inRange(img, min, max)
print("img=\n",img)
print("mask=\n",mask)   #在min~max範圍內的就變255 範圍外的就變0

img=
 [[180  58 111  47 231]
 [ 98 209 119 132  47]
 [123  74  66  30  84]
 [233   7 115  38 118]
 [215 100 193  80 200]]
mask=
 [[255   0 255   0   0]
 [  0   0 255 255   0]
 [255   0   0   0   0]
 [  0   0 255   0 255]
 [  0 255 255   0 255]]


## Mask 遮罩  bitwise_and 只顯示符合的像素

In [4]:
import cv2
import numpy as np
img=np.ones([5,5],dtype=np.uint8) * 9
mask =np.zeros([5,5],dtype=np.uint8)
mask[0:3,0]=1
mask[2:5,2:4]=1

roi=cv2.bitwise_and(img,img, mask= mask) #.bitwise_and 視為二進位處理 兩個都有1的才是1
print("img=\n",img)
print("mask=\n",mask)
print("roi=\n",roi)

img=
 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
mask=
 [[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 1 1 0]
 [0 0 1 1 0]
 [0 0 1 1 0]]
roi=
 [[9 0 0 0 0]
 [9 0 0 0 0]
 [9 0 9 9 0]
 [0 0 9 9 0]
 [0 0 9 9 0]]


### 假設感興趣的區間是 以下
- Blue: (110, 50, 50) - (130, 255, 255)
- Green: (50, 100, 100) - (70, 255, 255)
- Red: (0,100,100) - (10, 255, 255)

In [8]:
import cv2
import numpy as np
opencv=cv2.imread("./images/opencv.jpg")
hsv = cv2.cvtColor(opencv, cv2.COLOR_BGR2HSV)
cv2.imshow('opencv',opencv)

#=============blue range=============
minBlue = np.array([110,50,50])
maxBlue = np.array([130,255,255])
mask = cv2.inRange(hsv, minBlue, maxBlue) #在範圍內的都變255 不在變0 

blue = cv2.bitwise_and(opencv,opencv, mask= mask) #.bitwise_and 兩個都有1才是1
cv2.imshow('blue',blue)

#=============green range=============
minGreen = np.array([50,50,50])
maxGreen = np.array([70,255,255])
mask = cv2.inRange(hsv, minGreen, maxGreen)

green = cv2.bitwise_and(opencv,opencv, mask= mask)
cv2.imshow('green',green)

#=============red range=============
minRed = np.array([0,50,50])
maxRed = np.array([30,255,255])
mask = cv2.inRange(hsv, minRed, maxRed)

red= cv2.bitwise_and(opencv,opencv, mask= mask)
cv2.imshow('red',red)

cv2.waitKey()
cv2.destroyAllWindows()

### 假設 你想抓出皮膚色  (可上網找色碼)
- H: 5 - 170
- S: 25 - 166

In [1]:
import cv2
img=cv2.imread("./images/lesson2.jpg")
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
h,s,v=cv2.split(hsv) #分3張

minHue=5
maxHue=170
hueMask=cv2.inRange(h, minHue, maxHue)

minSat=25
maxSat=166
satMask = cv2.inRange(s, minSat, maxSat)

mask = hueMask & satMask #兩個做bitwise_and

roi = cv2.bitwise_and(img,img, mask= mask)

cv2.imshow("img",img)
cv2.imshow("ROI",roi)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
import cv2
img=cv2.imread("./images/barbara.bmp")
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
h,s,v=cv2.split(hsv)
v[:,:]=255 #把V 變成255
newHSV=cv2.merge([h,s,v]) #三片合併
art = cv2.cvtColor(newHSV, cv2.COLOR_HSV2BGR)

cv2.imshow("img",img)
cv2.imshow("art",art)
cv2.waitKey()
cv2.destroyAllWindows()