## Erode  侵蝕 (內壁)

In [4]:
import cv2
import numpy as np
img=np.zeros((5,5),np.uint8)
img[1:4,1:4]=1
kernel = np.ones((3,1),np.uint8)
erosion = cv2.erode(img,kernel)
print("img=\n",img)
print("kernel=\n",kernel)
print("erosion=\n",erosion)

img=
 [[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
kernel=
 [[1]
 [1]
 [1]]
erosion=
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [5]:
import cv2
import numpy as np
o=cv2.imread("./images/erode.bmp",cv2.IMREAD_UNCHANGED)
kernel = np.ones((5,5),np.uint8) #5*5 都是1的
erosion = cv2.erode(o,kernel) 

cv2.imshow("orriginal",o)
cv2.imshow("erosion",erosion)
cv2.waitKey()
cv2.destroyAllWindows()

In [2]:
import cv2
import numpy as np
o=cv2.imread("./images/erode.bmp",cv2.IMREAD_UNCHANGED)
kernel = np.ones((9,9),np.uint8)
erosion = cv2.erode(o,kernel,iterations =5) #侵蝕5次
cv2.imshow("orriginal",o)
cv2.imshow("erosion",erosion)
cv2.waitKey()
cv2.destroyAllWindows()

## Dilate 膨脹(外壁)

In [6]:
import cv2
import numpy as np
img=np.zeros((5,5),np.uint8)
img[2:3,1:4]=1
kernel = np.ones((3,1),np.uint8)  #正中心的1 對在img的1 滑
dilation = cv2.dilate(img,kernel)
print("img=\n",img)
print("kernel=\n",kernel)
print("dilation\n",dilation)

img=
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
kernel=
 [[1]
 [1]
 [1]]
dilation
 [[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [6]:
import cv2
import numpy as np
o=cv2.imread("./images/dilation.bmp",cv2.IMREAD_UNCHANGED)
kernel = np.ones((9,9),np.uint8)
dilation = cv2.dilate(o,kernel)
cv2.imshow("original",o)
cv2.imshow("dilation",dilation)
cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
import cv2
import numpy as np
o=cv2.imread("./images/dilation.bmp",cv2.IMREAD_UNCHANGED)
kernel = np.ones((5,5),np.uint8)
dilation = cv2.dilate(o,kernel,iterations = 9) #iterations疊代 膨脹9次
cv2.imshow("original",o)
cv2.imshow("dilation", dilation)
cv2.waitKey()
cv2.destroyAllWindows()

## Open (開運算) 先侵蝕 再膨脹 圖就不會變小

In [8]:
import cv2
import numpy as np
img1=cv2.imread("./images/opening.bmp")
img2=cv2.imread("./images/opening2.bmp")

k=np.ones((10,10),np.uint8)
r1=cv2.morphologyEx(img1,cv2.MORPH_OPEN,k)
r2=cv2.morphologyEx(img2,cv2.MORPH_OPEN,k)

cv2.imshow("img1",img1)
cv2.imshow("result1",r1) # 去掉毛邊 但又補回粗度
cv2.imshow("img2",img2)
cv2.imshow("result2",r2)
cv2.waitKey()
cv2.destroyAllWindows()

## Close (閉運算) 先膨脹再侵蝕 可遮掉裡面的缺點

In [9]:
import cv2
import numpy as np
img1=cv2.imread("./images/closing.bmp")
img2=cv2.imread("./images/closing2.bmp")

k=np.ones((10,10),np.uint8)
r1=cv2.morphologyEx(img1,cv2.MORPH_CLOSE,k,iterations=3)
r2=cv2.morphologyEx(img2,cv2.MORPH_CLOSE,k,iterations=3)

cv2.imshow("img1",img1)
cv2.imshow("result1",r1)
cv2.imshow("img2",img2)
cv2.imshow("result2",r2)
cv2.waitKey()
cv2.destroyAllWindows()

## Gradient 留邊

In [10]:
import cv2
import numpy as np
o=cv2.imread("./images/gradient.bmp",cv2.IMREAD_UNCHANGED)

k=np.ones((5,5),np.uint8)
r=cv2.morphologyEx(o,cv2.MORPH_GRADIENT,k)

cv2.imshow("original",o)
cv2.imshow("result",r)
cv2.waitKey()
cv2.destroyAllWindows()

## Tophat 原始照片 減掉 開運算照片

In [11]:
import cv2
import numpy as np
o1=cv2.imread("./images/tophat.bmp",cv2.IMREAD_UNCHANGED)
o2=cv2.imread("./images/lena.bmp",cv2.IMREAD_UNCHANGED)

k=np.ones((5,5),np.uint8)
r1=cv2.morphologyEx(o1,cv2.MORPH_TOPHAT,k)
r2=cv2.morphologyEx(o2,cv2.MORPH_TOPHAT,k)

cv2.imshow("original1",o1)
cv2.imshow("original2",o2)
cv2.imshow("result1",r1)
cv2.imshow("result2",r2)
cv2.waitKey()
cv2.destroyAllWindows()

## Blackhat 原始照片 減掉 閉運算

In [12]:
import cv2
import numpy as np
o1=cv2.imread("./images/blackhat.bmp",cv2.IMREAD_UNCHANGED)
o2=cv2.imread("./images/lena.bmp",cv2.IMREAD_UNCHANGED)
k=np.ones((5,5),np.uint8)
r1=cv2.morphologyEx(o1,cv2.MORPH_BLACKHAT,k)
r2=cv2.morphologyEx(o2,cv2.MORPH_BLACKHAT,k)
cv2.imshow("original1",o1)
cv2.imshow("original2",o2)
cv2.imshow("result1",r1)
cv2.imshow("result2",r2)
cv2.waitKey()
cv2.destroyAllWindows()

## Define Own Kernel  自定義 kernel

In [21]:
import cv2
kernel1 = cv2.getStructuringElement(cv2.MORPH_RECT, (5,5))  # MORPH_RECT方形
kernel2 = cv2.getStructuringElement(cv2.MORPH_CROSS,  (5,5)) # MORPH_CROSS十字形
kernel3 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,  (5,5)) #MORPH_ELLIPSE橢圓
print("kernel1=\n",kernel1)
print("kernel2=\n",kernel2)
print("kernel3=\n",kernel3)

kernel1=
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
kernel2=
 [[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
kernel3=
 [[0 0 1 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 0 0]]
