#### 取絕對值

In [1]:
import cv2
import numpy as np
img=np.random.randint(-256,256,size=[4,5],dtype=np.int16) #從-256~256 256不算，隨機
rst=cv2.convertScaleAbs(img)  #.convertScaleAbs 取絕對值
print("img=\n",img)
print("rst=\n",rst)

img=
 [[-180  235  152    0 -123]
 [  11   11  248   37  245]
 [-255  255  103  122   -4]
 [-114 -126  223  191 -111]]
rst=
 [[180 235 152   0 123]
 [ 11  11 248  37 245]
 [255 255 103 122   4]
 [114 126 223 191 111]]


## Sobel 一階維分 (指3*3的矩陣)
- x軸

In [2]:
import cv2
o = cv2.imread('./images/sobel4.bmp',cv2.IMREAD_GRAYSCALE)

sobelx = cv2.Sobel(o,-1,1,0) # 1,0 對x作微分
#發現 有些x邊沒出現，因為在做維分時 變成負數 就不會出現

cv2.imshow("original",o)
cv2.imshow("x",sobelx)
cv2.waitKey()
cv2.destroyAllWindows()

In [1]:
import cv2
o = cv2.imread('./images/sobel4.bmp',cv2.IMREAD_GRAYSCALE)
sobelx = cv2.Sobel(o,cv2.CV_64F,1,0)

 #.convertScaleAbs 取絕對值 才能取到所有x邊
sobelx = cv2.convertScaleAbs(sobelx)   # 轉回uint8  

cv2.imshow("original",o)
cv2.imshow("x",sobelx)
cv2.waitKey()
cv2.destroyAllWindows()

- y軸

In [2]:
import cv2
o = cv2.imread('./images/sobel4.bmp',cv2.IMREAD_GRAYSCALE)

sobely = cv2.Sobel(o,cv2.CV_64F,0,1) # 0,1 對y作微分
sobely = cv2.convertScaleAbs(sobely)
cv2.imshow("original",o)

cv2.imshow("y",sobely)
cv2.waitKey()
cv2.destroyAllWindows()

- x y 軸

In [13]:
import cv2
o = cv2.imread('./images/sobel4.bmp',cv2.IMREAD_GRAYSCALE)

sobelxy=cv2.Sobel(o,cv2.CV_64F,1,1) # 1,1對xy一起做微分
sobelxy=cv2.convertScaleAbs(sobelxy) 
cv2.imshow("original",o)

cv2.imshow("xy",sobelxy)
cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
import cv2
o = cv2.imread('./images/sobel4.bmp',cv2.IMREAD_GRAYSCALE)

sobelx = cv2.Sobel(o,cv2.CV_64F,1,0) # 先對x
sobely = cv2.Sobel(o,cv2.CV_64F,0,1) # 再對y
sobelx = cv2.convertScaleAbs(sobelx) 
sobely = cv2.convertScaleAbs(sobely)  

#加權平均，把xy合併 且顯示的重量平均
sobelxy =  cv2.addWeighted(sobelx,0.5,sobely,0.1,0) 

cv2.imshow("original",o)
cv2.imshow("xy",sobelxy)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
import cv2
o = cv2.imread('./images/lena.bmp',cv2.IMREAD_GRAYSCALE)

sobelx = cv2.Sobel(o,cv2.CV_64F,1,0)
sobely = cv2.Sobel(o,cv2.CV_64F,0,1)
sobelx = cv2.convertScaleAbs(sobelx)  
sobely = cv2.convertScaleAbs(sobely)  

 #加權平均，把xy合併 且顯示的重量平均
sobelxy =  cv2.addWeighted(sobelx,0.5,sobely,0.5,0) 

sobelxy11=cv2.Sobel(o,cv2.CV_64F,1,1) #又把xy在做一次維分
sobelxy11=cv2.convertScaleAbs(sobelxy11) 

cv2.imshow("original",o)
cv2.imshow("xy",sobelxy)
cv2.imshow("xy11",sobelxy11)
cv2.waitKey()
cv2.destroyAllWindows()

## Scharr 一階維分 只是倍數比sobel大

In [14]:
import cv2
o = cv2.imread('./images/scharr.bmp',cv2.IMREAD_GRAYSCALE)
scharrx = cv2.Scharr(o,cv2.CV_64F,1,0)
scharrx = cv2.convertScaleAbs(scharrx)   # 轉回uint8 
cv2.imshow("original",o)
cv2.imshow("x",scharrx)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
import cv2
o = cv2.imread('./images/scharr.bmp',cv2.IMREAD_GRAYSCALE)
scharry = cv2.Scharr(o,cv2.CV_64F,0,1)
scharry = cv2.convertScaleAbs(scharry)  
cv2.imshow("original",o)
cv2.imshow("y",scharry)
cv2.waitKey()
cv2.destroyAllWindows()

In [15]:
import cv2
o = cv2.imread('./images/scharr.bmp',cv2.IMREAD_GRAYSCALE)
scharrx = cv2.Scharr(o,cv2.CV_64F,1,0)
scharry = cv2.Scharr(o,cv2.CV_64F,0,1)
scharrx = cv2.convertScaleAbs(scharrx)   # 轉回uint8 
scharry = cv2.convertScaleAbs(scharry)  
scharrxy =  cv2.addWeighted(scharrx,0.5,scharry,0.5,0)  
cv2.imshow("original",o)
cv2.imshow("xy",scharrxy)
cv2.waitKey()
cv2.destroyAllWindows()

## Compare Sobel and Scharr 比較

In [16]:
import cv2
o = cv2.imread('./images/lena.bmp',cv2.IMREAD_GRAYSCALE)

sobelx = cv2.Sobel(o,cv2.CV_64F,1,0,ksize=3)
sobely = cv2.Sobel(o,cv2.CV_64F,0,1,ksize=3)
sobelx = cv2.convertScaleAbs(sobelx)   
sobely = cv2.convertScaleAbs(sobely) 
sobelxy =  cv2.addWeighted(sobelx,0.5,sobely,0.5,0) 

scharrx = cv2.Scharr(o,cv2.CV_64F,1,0)
scharry = cv2.Scharr(o,cv2.CV_64F,0,1)
scharrx = cv2.convertScaleAbs(scharrx)  
scharry = cv2.convertScaleAbs(scharry)  
scharrxy =  cv2.addWeighted(scharrx,0.5,scharry,0.5,0) 

cv2.imshow("original",o)
cv2.imshow("sobelxy",sobelxy)
cv2.imshow("scharrxy",scharrxy)
cv2.waitKey()
cv2.destroyAllWindows()

## Laplacian 二階微分

In [17]:
import cv2
o = cv2.imread('./images/Laplacian.bmp',cv2.IMREAD_GRAYSCALE)
Laplacian = cv2.Laplacian(o,cv2.CV_64F)
Laplacian = cv2.convertScaleAbs(Laplacian)   

cv2.imshow("original",o)
cv2.imshow("Laplacian",Laplacian)
cv2.waitKey()
cv2.destroyAllWindows()

## Canny 邊緣偵測算法

In [12]:
import cv2
o=cv2.imread("./images/lena.bmp",cv2.IMREAD_GRAYSCALE)
r1=cv2.Canny(o,128,200) # 決定濾波器的 最小值,最大值
r2=cv2.Canny(o,32,128) # 最小值,最大值 (訂的比較寬鬆，所以畫出來比較多邊)
cv2.imshow("original",o)
cv2.imshow("result1",r1)
cv2.imshow("result2",r2)
cv2.waitKey()
cv2.destroyAllWindows()