# cv2.findContours 找輪廓
第二个参数表示轮廓的检索模式，有四种
- cv2.RETR_EXTERNAL 只检测外轮廓
- cv2.RETR_LIST 检测的轮廓不建立等级关系
- cv2.RETR_CCOMP 建立两个等级的轮廓，上面的一层为外边界，里面的一层为内孔的边界信息。如果内孔内还有一个连通物体，这个物体的边界也在顶层。
- cv2.RETR_TREE 建立一个等级树结构的轮廓。

第三个参数method为轮廓的近似办法
- cv2.CHAIN_APPROX_NONE 存储所有的轮廓点，相邻的两个点的像素位置差不超过1，即max（abs（x1-x2），abs（y2-y1））==1
- cv2.CHAIN_APPROX_SIMPLE 压缩水平方向，垂直方向，对角线方向的元素，只保留该方向的终点坐标，例如一个矩形轮廓只需4个点来保存轮廓信息
- cv2.CHAIN_APPROX_TC89_L1，CV_CHAIN_APPROX_TC89_KCOS 使用teh-Chinl chain 近似算法

In [3]:
import cv2
o = cv2.imread('./images/contours.bmp')  
cv2.imshow("original",o)

gray = cv2.cvtColor(o,cv2.COLOR_BGR2GRAY) #轉成灰階 
ret, binary = cv2.threshold(gray,127,255,cv2.THRESH_BINARY) #超过127門檻部分取maxval（最大值），否则取0  
contours, hierarchy = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) 

# print(type(contours))  
# print(type(contours[0]))  

print('number fo contours {}'.format(len(contours))) #問有幾個輪廓
print('first contour coordinate {}'.format(contours[0])) # 問第0個輪廓的點 有哪些

#print(contours[1].shape)

o=cv2.drawContours(o,contours,-1,(0,0,255),5)  #畫輪廓 

cv2.imshow("result",o)    
cv2.waitKey()
cv2.destroyAllWindows()

number fo contours 3
first contour coordinate [[[ 79 270]]

 [[ 79 383]]

 [[195 383]]

 [[195 270]]]


In [4]:
import cv2
import numpy as np
o = cv2.imread('./images/contours.bmp')  
cv2.imshow("original",o)
gray = cv2.cvtColor(o,cv2.COLOR_BGR2GRAY) #變灰階 
ret, binary = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)  
contours, hierarchy = cv2.findContours(binary,
                                             cv2.RETR_EXTERNAL,
                                             cv2.CHAIN_APPROX_SIMPLE)  
n=len(contours)
contoursImg=[]
for i in range(n): #有幾個輪廓 就做幾次
    temp=np.zeros(o.shape,np.uint8)
    contoursImg.append(temp)
    contoursImg[i]=cv2.drawContours(contoursImg[i],contours,i,(255,255,255),5) 
    cv2.imshow("contours[" + str(i)+"]",contoursImg[i])    
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
import cv2
import numpy as np
o = cv2.imread('./images/loc3.jpg')
cv2.imshow("original",o)  
gray = cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)  
ret, binary = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)  
contours, hierarchy = cv2.findContours(binary, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)  

mask=np.zeros(o.shape,np.uint8) #跟原圖大小一樣的形狀 裡面塞0
mask=cv2.drawContours(mask,contours,-1,(255,255,255),-1) # 顏色.粗度-1是實心

cv2.imshow("mask" ,mask)
loc=cv2.bitwise_and(o,mask) 

cv2.imshow("location" ,loc)
cv2.waitKey()
cv2.destroyAllWindows()

- 算輪廓面積 cv2.contourArea

In [6]:
import cv2
import numpy as np
o = cv2.imread('./images/contours.bmp')  
gray = cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)  
ret, binary = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)  
contours, hierarchy = cv2.findContours(binary,
                                             cv2.RETR_LIST,
                                             cv2.CHAIN_APPROX_SIMPLE)  
cv2.imshow("original",o)
n=len(contours)
contoursImg=[]
for i in range(n):
    print("contours["+str(i)+"] 面積=",cv2.contourArea(contours[i])) #.contourArea算面積
    temp=np.zeros(o.shape,np.uint8)
    contoursImg.append(temp)
    contoursImg[i]=cv2.drawContours(contoursImg[i],
                                   contours,
                                   i,
                                   (255,255,255),
                                   3)
    cv2.imshow("contours[" + str(i)+"]",contoursImg[i])   
cv2.waitKey()
cv2.destroyAllWindows()

contours[0] 面積= 13108.0
contours[1] 面積= 19535.0
contours[2] 面積= 12058.0


- 算輪廓長度 cv2.arcLength

In [7]:
import cv2
import numpy as np
#--------------读取及显示原始图像--------------------
o = cv2.imread('./images/contours0.bmp')  
cv2.imshow("original",o)

#--------------获取轮廓--------------------
gray = cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)  
ret, binary = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)  
contours, hierarchy = cv2.findContours(binary,
                                             cv2.RETR_LIST,
                                             cv2.CHAIN_APPROX_SIMPLE)  

#--------------计算各个轮廓的长度和、平均长度--------------------
n=len(contours)   #获取轮廓个数
cntLen=[]           #存储各个轮廓的长度
for i in range(n):
    cntLen.append(cv2.arcLength(contours[i],True))
    print("第"+str(i)+"个轮廓的长度:%d"%cntLen[i])
cntLenSum=np.sum(cntLen)  #各个轮廓长度和
cntLenAvr=cntLenSum/n    #各个轮廓长度平均值
print("各个轮廓的总长度为：%d"%cntLenSum)
print("各个轮廓的平均长度为：%d"%cntLenAvr)

#--------------显示超过平均值的轮廓--------------------
contoursImg=[]
for i in range(n):
    temp=np.zeros(o.shape,np.uint8)
    contoursImg.append(temp)
    contoursImg[i]=cv2.drawContours(contoursImg[i],
               contours,i,(255,255,255),3)
    if cv2.arcLength(contours[i],True)>cntLenAvr:
        cv2.imshow("contours[" + str(i)+"]",contoursImg[i])  
        
cv2.waitKey()
cv2.destroyAllWindows()

第0个轮廓的长度:145
第1个轮廓的长度:147
第2个轮廓的长度:398
第3个轮廓的长度:681
第4个轮廓的长度:1004
第5个轮廓的长度:398
第6个轮廓的长度:681
第7个轮廓的长度:1004
第8个轮廓的长度:2225
第9个轮廓的长度:2794
各个轮廓的总长度为：9480
各个轮廓的平均长度为：948


# Moments(矩) 找質心的重心 算面積
#### 跟.contourArea算出的面積一樣
![image alt](./images/moments_theory.png)

In [8]:
import cv2
import numpy as np
o = cv2.imread('./images/moments.bmp') 
cv2.imshow("original",o)

gray = cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)  
ret, binary = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)  
contours, hierarchy = cv2.findContours(binary, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)  

n=len(contours)
contoursImg=[]
for i in range(n):
    temp=np.zeros(o.shape,np.uint8)
    contoursImg.append(temp)
    contoursImg[i]=cv2.drawContours(contoursImg[i],contours,i,255,3) 
    cv2.imshow("contours[" + str(i)+"]",contoursImg[i]) 
    
    
print("观察各个轮廓的矩（moments）:")
for i in range(n):
    print("轮廓"+str(i)+"的矩:\n",cv2.moments(contours[i]))
    
    
print("观察各个轮廓的面积:")
for i in range(n):
    print("轮廓"+str(i)+"的面积:%d" %cv2.moments(contours[i])['m00'])
    
cv2.waitKey()
cv2.destroyAllWindows()

观察各个轮廓的矩（moments）:
轮廓0的矩:
 {'m00': 14900.0, 'm10': 1996600.0, 'm01': 7800150.0, 'm20': 279961066.6666666, 'm11': 1045220100.0, 'm02': 4110944766.6666665, 'm30': 40842449600.0, 'm21': 146559618400.0, 'm12': 550866598733.3334, 'm03': 2180941440375.0, 'mu20': 12416666.666666627, 'mu11': 0.0, 'mu02': 27566241.666666508, 'mu30': 1.52587890625e-05, 'mu21': 2.09808349609375e-05, 'mu12': 6.198883056640625e-05, 'mu03': 0.000244140625, 'nu20': 0.05592841163310942, 'nu11': 0.0, 'nu02': 0.12416666666666591, 'nu30': 5.630596400372416e-16, 'nu21': 7.742070050512072e-16, 'nu12': 2.2874297876512943e-15, 'nu03': 9.008954240595866e-15}
轮廓1的矩:
 {'m00': 34314.0, 'm10': 13313832.0, 'm01': 9728019.0, 'm20': 5356106574.0, 'm11': 3774471372.0, 'm02': 2808475082.0, 'm30': 2225873002920.0, 'm21': 1518456213729.0, 'm12': 1089688331816.0, 'm03': 824882507095.5, 'mu20': 190339758.0, 'mu11': 0.0, 'mu02': 50581695.5, 'mu30': 0.0, 'mu21': 0.0, 'mu12': 0.0, 'mu03': 0.0, 'nu20': 0.16165413533834588, 'nu11': 0.0, 'nu02'

# Hu moment 
## 適合用來辨識照片裡的東西一不一樣 (S算出的數據幾乎都相同，代表他們很相似)

![image alt](./images/hu_theory.png)

![image alt](./images/hu.png)

### matchShapes

In [9]:
import cv2
#--------------读取3幅原始图像--------------------
o1 = cv2.imread('./images/cs1.bmp')
o2 = cv2.imread('./images/cs2.bmp')
o3 = cv2.imread('./images/cc.bmp') 

#----------打印3幅原始图像的shape属性值-------------
print("o1.shape=",o1.shape)
print("o2.shape=",o2.shape)
print("o3.shape=",o3.shape)

#--------------色彩空间转换-------------------- 
gray1 = cv2.cvtColor(o1,cv2.COLOR_BGR2GRAY) 
gray2 = cv2.cvtColor(o2,cv2.COLOR_BGR2GRAY) 
gray3 = cv2.cvtColor(o3,cv2.COLOR_BGR2GRAY) 

#-------------进行Hu矩匹配--------------------
ret0 = cv2.matchShapes(gray1,gray1,1,0.0) #(照片1,照片2)用hu moment算相似度
ret1 = cv2.matchShapes(gray1,gray2,1,0.0)
ret2 = cv2.matchShapes(gray1,gray3,1,0.0)

#--------------打印差值--------------------
print("相同图像的matchShape=",ret0)  # 0 代表完全相同
print("相似图像的matchShape=",ret1)  # 越接近0  代表越相似
print("不相似图像的matchShape=",ret2)

#--------------显示3幅原始图像--------------------
cv2.imshow("original1",o1)
cv2.imshow("original2",o2)
cv2.imshow("original3",o3)
cv2.waitKey()
cv2.destroyAllWindows()

o1.shape= (425, 514, 3)
o2.shape= (42, 51, 3)
o3.shape= (425, 514, 3)
相同图像的matchShape= 0.0
相似图像的matchShape= 0.0001154058519395873
不相似图像的matchShape= 0.012935752303635195


# ref  把物體用框框匡出來 用成灰階算輪廓 抓重心
https://chtseng.wordpress.com/2016/12/05/opencv-contour%E8%BC%AA%E5%BB%93/

In [10]:
import cv2
import numpy as np

o = cv2.imread('./images/stuff.jpg')
cv2.imshow("original",o)  
cv2.waitKey()
cv2.destroyAllWindows()