# HaarCascade  人臉偵測 (只是把人臉框出來)
xml download: https://github.com/opencv/opencv/tree/master/data/haarcascades  
more haar example: https://www.bogotobogo.com/python/OpenCV_Python/python_opencv3_Image_Object_Detection_Face_Detection_Haar_Cascade_Classifiers.php

In [3]:
import cv2

image = cv2.imread('./images/dface3.jpg')
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

# 取得xml文件,加載人臉檢視器
faceCascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')


# 调用函数detectMultiScale
faces = faceCascade.detectMultiScale(
    gray,
    scaleFactor = 1.15,
    minNeighbors = 5,
    minSize = (5,5)
)
print(faces) #(x,y,w寬,h高)

#打印输出测试结果
print("发现{}个人脸!".format(len(faces)))

#逐个标记人脸
for(x,y,w,h) in faces:
    
    #畫框框                   
    cv2.rectangle(image,(x,y),(x+w,y+w),(0,255,0),2) 
    
    #畫圓圈                       座標點                半徑      顏色  粗度
#     cv2.circle(image,(int((x+x+w)/2),int((y+y+h)/2)),int(w/2),(0,255,0),2)


cv2.imshow("dect",image)
cv2.imwrite("re.jpg",image) #存檔

cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 36  77  61  61]
 [289  12  77  77]
 [566  65  62  62]
 [444  63  68  68]
 [129  60  61  61]]
发现5个人脸!


# LBPH 人臉辨識(辨認身份)

In [9]:
import cv2
import numpy as np

images=[]
images.append(cv2.imread("./images/a1.png",cv2.IMREAD_GRAYSCALE))
images.append(cv2.imread("./images/a2.png",cv2.IMREAD_GRAYSCALE))
images.append(cv2.imread("./images/b1.png",cv2.IMREAD_GRAYSCALE))
images.append(cv2.imread("./images/b2.png",cv2.IMREAD_GRAYSCALE))
labels=[0,0,1,1]  #把第1.2照片設為 id 0這個人 ，把第3.4照片設為id 1這個人

#訓練模型
recognizer = cv2.face.LBPHFaceRecognizer_create()
recognizer.train(images, np.array(labels))  

#測試：把a3這張照片拿去跟模型比對
predict_image=cv2.imread("./images/a3.png",cv2.IMREAD_GRAYSCALE) 
label,confidence= recognizer.predict(predict_image) 
print("label=",label) # 測出是誰
print("confidence=",confidence) #信心度


label= 0
confidence= 67.6856704732354


# EigenFaces 人臉辨識(辨認身份)

In [10]:
import cv2
import numpy as np

images=[]
images.append(cv2.imread("./images/e01.png",cv2.IMREAD_GRAYSCALE))
images.append(cv2.imread("./images/e02.png",cv2.IMREAD_GRAYSCALE))
images.append(cv2.imread("./images/e11.png",cv2.IMREAD_GRAYSCALE))
images.append(cv2.imread("./images/e12.png",cv2.IMREAD_GRAYSCALE))
labels=[0,0,1,1]

#訓練模型
recognizer = cv2.face.EigenFaceRecognizer_create()
recognizer.train(images, np.array(labels)) 

#測試
predict_image=cv2.imread("./images/eTest.png",cv2.IMREAD_GRAYSCALE)
label,confidence= recognizer.predict(predict_image) 
print("label=",label)
print("confidence=",confidence)


label= 0
confidence= 1600.5481032349048


# Fisherfaces 人臉辨識(辨認身份)

In [11]:
import cv2
import numpy as np

images=[]
images.append(cv2.imread("./images/f01.png",cv2.IMREAD_GRAYSCALE))
images.append(cv2.imread("./images/f02.png",cv2.IMREAD_GRAYSCALE))
images.append(cv2.imread("./images/f11.png",cv2.IMREAD_GRAYSCALE))
images.append(cv2.imread("./images/f12.png",cv2.IMREAD_GRAYSCALE))
labels=[0,0,1,1]

recognizer = cv2.face.FisherFaceRecognizer_create()
recognizer.train(images, np.array(labels))  

predict_image=cv2.imread("./images/fTest.png",cv2.IMREAD_GRAYSCALE)
label,confidence= recognizer.predict(predict_image) 
print("label=",label)
print("confidence=",confidence)


label= 0
confidence= 92.5647623298737
